---
- name: Wordpress | install epel-release, remirepo
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Wordpress | Install apache, php
  become: true
  ansible.builtin.yum:
    state: present
    name:
      - httpd
      - php
      - php-mysql
      - php-gd
    enablerepo:
      - remi-php74

- name: Wordpress | Apache systemd service
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
