---
- name: Prometheus | Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled

- name: Node Exporter | Create nodeexporter group
  become: true
  ansible.builtin.group:
    name: nodeexporter
    system: true
    state: present

- name: Node Exporter | Create nodeexporter user
  become: true
  ansible.builtin.user:
    name: nodeexporter
    create_home: false
    shell: "/usr/sbin/nologin"
    group: nodeexporter
    system: true
    state: present
    home: "{{ nodeexporter_folder }}"

- name: Node Exporter | Create directory for nodeexporter
  become: true
  ansible.builtin.file:
    state: directory
    owner: nodeexporter
    group: nodeexporter
    mode: 0755
    path: "{{ nodeexporter_folder }}"

- name: Node Exporter | Create configuration directory for nodeexporter
  become: true
  ansible.builtin.file:
    state: directory
    owner: root
    group: nodeexporter
    mode: 0770
    path: "{{ nodeexporter_config_folder }}"

- name: Download and unarchive nodeexporter
  block:
    - name: Node Exporter | Download archive
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ nodeexp_version }}/node_exporter-{{ nodeexp_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ nodeexp_version }}.linux-amd64.tar.gz"
        mode: 0755

    - name: Node Exporter | Unarchive nodeexporter tar.gz
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ nodeexp_version }}.linux-amd64.tar.gz"
        dest: /tmp
        mode: 0755
        remote_src: true

    - name: Node Exporter | Copy binary to bin folder
      become: true
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ nodeexp_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: nodeexporter
        group: nodeexporter
        remote_src: true
      loop:
        - node_exporter
  when:
    - nodeexporter_install

- name: Node Exporter | Create service unit
  become: true
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: reload nodeexporter service
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    daemon_reload: true
    state: restarted
