---
# tasks file for mysql-cluster-role
- include_tasks: install_mysql.yml
  when: install_mysql
- include_tasks: initial_setup.yml
  when: initial_setup
- include_tasks: replication.yml
- include_tasks: create_db_and_user.yml
  when:
    - mysql_create_db
    - mysql_replication_role == 'primary'
