---
- name: Prometheus | Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled

- name: Mysqld Exporter | Create Mysqld Exporter group
  become: true
  ansible.builtin.group:
    name: mysqldexporter
    system: true
    state: present

- name: Mysqld Exporter | Create Mysqld Exporter user
  become: true
  ansible.builtin.user:
    name: mysqldexporter
    create_home: false
    shell: "/usr/sbin/nologin"
    group: mysqldexporter
    system: true
    state: present
    home: "{{ mysqldexporter_folder }}"

- name: Mysqld Exporter | Create directory for Mysqld Exporter
  become: true
  ansible.builtin.file:
    state: directory
    owner: mysqldexporter
    group: mysqldexporter
    mode: 0755
    path: "{{ mysqldexporter_folder }}"

- name: Mysqld Exporter | Create configuration directory for Mysqld Exporter
  become: true
  ansible.builtin.file:
    state: directory
    owner: root
    group: mysqldexporter
    mode: 0770
    path: "{{ mysqldexporter_config_folder }}"

- name: Download and unarchive Mysqld Exporter
  block:
    - name: Mysqld Exporter | Download archive
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqldexporter_version }}/mysqld_exporter-{{ mysqldexporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/mysqld_exporter-{{ mysqldexporter_version }}.linux-amd64.tar.gz"
        mode: 0755

    - name: Mysqld Exporter | Unarchive Mysqld Exporter tar.gz
      ansible.builtin.unarchive:
        src: "/tmp/mysqld_exporter-{{ mysqldexporter_version }}.linux-amd64.tar.gz"
        dest: /tmp
        mode: 0755
        remote_src: true

    - name: Mysqld Exporter | Copy binary to bin folder
      become: true
      ansible.builtin.copy:
        src: "/tmp/mysqld_exporter-{{ mysqldexporter_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: mysqldexporter
        group: mysqldexporter
        remote_src: true
      loop:
        - mysqld_exporter
  when:
    - mysqldexporter_install

- name: Mysqld Exporter | Create service unit
  become: true
  ansible.builtin.template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Mysqld Exporter | Create MySQL user for Exporter
  community.mysql.mysql_user:
    state: present
    host: "%"
    name: "{{ mysqldexporter_mysql_user }}"
    password: "{{ mysqldexporter_mysql_pass }}"
    login_user: "{{ mysqldexporter_mysql_login_user }}"
    login_password: "{{ mysqldexporter_mysql_login_pass }}"
    priv:
      "*.*:PROCESS, REPLICATION CLIENT, SELECT"
  no_log: true

- name: Mysqld Exporter | Copy cnf file to conf directory
  become: true
  ansible.builtin.template:
    src: .mysqld_exporter.cnf.j2
    dest: "{{ mysqldexporter_config_folder }}/.mysqld_exporter.cnf"
    mode: 0600
    owner: mysqldexporter
    group: mysqldexporter
  no_log: true

- name: reload mysqld_exporter service
  become: true
  ansible.builtin.systemd:
    name: mysqld_exporter
    enabled: true
    daemon_reload: true
    state: restarted
